import { EARTH_RADIUS_SCENE } from "./constants";
import { latLonToScene, type ScenePosition } from "./coordinates";

export type LaunchSiteType =
  | "gov"         // national space agency
  | "commercial"  // private / commercial operator
  | "test"        // propulsion test / support facility
  | "planned"     // under construction / not yet operational
  | "historical"; // no longer conducting launches

export interface LaunchSite {
  id: string;
  name: string;
  shortName: string;
  lat: number;
  lon: number;
  country: string;
  agency: string;
  firstLaunch: number;
  type: LaunchSiteType;
  description: string;
}

// Dot colours per type
export const SITE_TYPE_COLOR: Record<LaunchSiteType, string> = {
  gov:        "#f59e0b", // amber
  commercial: "#38bdf8", // sky blue
  test:       "#4ade80", // green
  planned:    "#a78bfa", // violet
  historical: "#94a3b8", // slate
};

export const SITE_TYPE_LABEL: Record<LaunchSiteType, string> = {
  gov:        "Gov / National",
  commercial: "Commercial",
  test:       "Test / Support",
  planned:    "Planned",
  historical: "Historical",
};

export const LAUNCH_SITES: LaunchSite[] = [
  // ── United States ────────────────────────────────────────────────
  {
    id: "ksc",
    name: "Kennedy Space Center / LC-39A",
    shortName: "KSC",
    lat: 28.5622,
    lon: -80.5772,
    country: "USA",
    agency: "NASA / SpaceX",
    firstLaunch: 1967,
    type: "gov",
    description: "Home of Apollo, Space Shuttle, and SpaceX Falcon 9/Heavy. LC-39A now supports Starship integrated flight tests.",
  },
  {
    id: "canaveral",
    name: "Cape Canaveral SFS",
    shortName: "CC SFS",
    lat: 28.3922,
    lon: -80.6077,
    country: "USA",
    agency: "USSF / SpaceX / ULA",
    firstLaunch: 1950,
    type: "gov",
    description: "America's oldest active launch site. Hosts Atlas V, Vulcan, Falcon 9, and multiple USSF national security missions.",
  },
  {
    id: "starbase",
    name: "SpaceX Starbase (Boca Chica)",
    shortName: "Starbase",
    lat: 25.9969,
    lon: -97.1547,
    country: "USA",
    agency: "SpaceX",
    firstLaunch: 2021,
    type: "commercial",
    description: "SpaceX's purpose-built Starship launch facility at the southern tip of Texas. Home to the world's most powerful rocket. Orbital flight tests began in 2023.",
  },
  {
    id: "vandenberg",
    name: "Vandenberg SFB",
    shortName: "Vandenberg",
    lat: 34.7420,
    lon: -120.5724,
    country: "USA",
    agency: "USSF / SpaceX",
    firstLaunch: 1959,
    type: "gov",
    description: "Primary US site for polar and sun-synchronous orbits. SpaceX Falcon 9 launches multiple Starlink and rideshare missions per year from SLC-4E.",
  },
  {
    id: "wallops",
    name: "Wallops Flight Facility / MARS",
    shortName: "Wallops",
    lat: 37.8394,
    lon: -75.4874,
    country: "USA",
    agency: "NASA / Northrop Grumman / Rocket Lab",
    firstLaunch: 1945,
    type: "gov",
    description: "NASA's oldest launch site and home of the Mid-Atlantic Regional Spaceport (MARS). Northrop Grumman Antares and Rocket Lab Electron (NROL missions) both operate here.",
  },
  {
    id: "blue-origin-tx",
    name: "Blue Origin Launch Site One",
    shortName: "BO West TX",
    lat: 31.4223,
    lon: -104.7575,
    country: "USA",
    agency: "Blue Origin",
    firstLaunch: 2015,
    type: "commercial",
    description: "Remote West Texas desert site for Blue Origin's New Shepard suborbital rocket. Completed 30+ successful crew and cargo missions including Jeff Bezos' first flight in 2021.",
  },
  {
    id: "spaceport-america",
    name: "Spaceport America",
    shortName: "Spaceport America",
    lat: 32.9904,
    lon: -106.9749,
    country: "USA",
    agency: "Virgin Galactic / others",
    firstLaunch: 2010,
    type: "commercial",
    description: "World's first purpose-built commercial spaceport in New Mexico's Jornada del Muerto desert. Primary operations site for Virgin Galactic's VSS Unity spaceplane.",
  },
  {
    id: "kodiak",
    name: "Pacific Spaceport Complex – Alaska",
    shortName: "Kodiak",
    lat: 57.4352,
    lon: -152.3378,
    country: "USA",
    agency: "AADC / ABL Space",
    firstLaunch: 1998,
    type: "commercial",
    description: "High-latitude site on Kodiak Island ideal for polar orbits. Conducted early Athena launches; ABL Space conducts RS1 launch attempts here.",
  },
  {
    id: "mojave",
    name: "Mojave Air and Space Port",
    shortName: "Mojave",
    lat: 34.9013,
    lon: -118.1516,
    country: "USA",
    agency: "Various (FAA-licensed)",
    firstLaunch: 2004,
    type: "commercial",
    description: "First FAA-licensed spaceport for horizontal launches. Home to SpaceShipOne (first private crewed spaceflight, 2004), and ongoing R&D for Virgin Galactic and other commercial firms.",
  },
  {
    id: "promontory",
    name: "Northrop Grumman Promontory Facility",
    shortName: "Promontory, UT",
    lat: 41.6216,
    lon: -112.4681,
    country: "USA",
    agency: "Northrop Grumman",
    firstLaunch: 1965,
    type: "test",
    description: "Utah's rocket powerhouse. Northrop Grumman (formerly ATK / Thiokol) manufactures and static-fires the largest solid rocket motors in the world here — Space Shuttle SRBs, Ares I/V, and SLS solid boosters were all tested at this site.",
  },
  {
    id: "stennis",
    name: "Stennis Space Center",
    shortName: "Stennis, MS",
    lat: 30.3628,
    lon: -89.5948,
    country: "USA",
    agency: "NASA / SpaceX / Aerojet Rocketdyne",
    firstLaunch: 1966,
    type: "test",
    description: "NASA's primary rocket engine test site in southern Mississippi. Every Space Shuttle main engine and all four RS-25 SLS engines are hot-fire tested here before flight. SpaceX also tests Raptor engines at Stennis.",
  },
  // ── Russia ───────────────────────────────────────────────────────
  {
    id: "baikonur",
    name: "Baikonur Cosmodrome",
    shortName: "Baikonur",
    lat: 45.9200,
    lon: 63.3420,
    country: "Kazakhstan",
    agency: "Roscosmos",
    firstLaunch: 1957,
    type: "gov",
    description: "World's first and most historic spaceport. Sputnik 1, Vostok 1 (Gagarin), and all Soyuz crewed missions launched here. Leased from Kazakhstan through 2050.",
  },
  {
    id: "plesetsk",
    name: "Plesetsk Cosmodrome",
    shortName: "Plesetsk",
    lat: 62.9270,
    lon: 40.6770,
    country: "Russia",
    agency: "Roscosmos / VKS",
    firstLaunch: 1966,
    type: "gov",
    description: "World's most prolific launch site by total mission count (~1,600 launches). High latitude ideal for polar reconnaissance orbits. Home of Soyuz-2, Rokot, and Angara rockets.",
  },
  {
    id: "vostochny",
    name: "Vostochny Cosmodrome",
    shortName: "Vostochny",
    lat: 51.8840,
    lon: 128.3330,
    country: "Russia",
    agency: "Roscosmos",
    firstLaunch: 2016,
    type: "gov",
    description: "Russia's newest and most modern cosmodrome, built on Russian soil in the Far East to reduce dependence on Baikonur. Soyuz-2 and future Angara-A5 heavy lift operate from here.",
  },
  {
    id: "kapustin-yar",
    name: "Kapustin Yar",
    shortName: "Kapustin Yar",
    lat: 48.5796,
    lon: 45.7553,
    country: "Russia",
    agency: "Roscosmos / VKS",
    firstLaunch: 1947,
    type: "gov",
    description: "Russia's second-oldest launch site, established for V-2 derivative rockets in 1947. Still active for small satellite launches on Kosmos-3M and military missions.",
  },
  {
    id: "yasny",
    name: "Yasny (Dombarovsky) Launch Base",
    shortName: "Yasny",
    lat: 51.2084,
    lon: 59.8518,
    country: "Russia",
    agency: "ISC Kosmotras / Roscosmos",
    firstLaunch: 2006,
    type: "gov",
    description: "Former ICBM silo repurposed for commercial Dnepr and Rokot launches. Launched Deimos-2, DubaiSat-2, and dozens of international small sats.",
  },
  // ── Europe ───────────────────────────────────────────────────────
  {
    id: "kourou",
    name: "Guiana Space Centre",
    shortName: "Kourou",
    lat: 5.2310,
    lon: -52.7690,
    country: "French Guiana",
    agency: "ESA / Arianespace / ArianeGroup",
    firstLaunch: 1968,
    type: "gov",
    description: "Europe's spaceport, just 5° above the equator. The location grants ~460 m/s of free velocity for GTO missions. Home of Ariane 5/6, Soyuz (2011–2022), and Vega rockets.",
  },
  {
    id: "esrange",
    name: "Esrange Space Center",
    shortName: "Esrange",
    lat: 67.8878,
    lon: 21.0854,
    country: "Sweden",
    agency: "SSC",
    firstLaunch: 1966,
    type: "gov",
    description: "Europe's northernmost launch site, 200 km above the Arctic Circle. Primarily sounding rockets and stratospheric balloons; now being upgraded for small orbital launches targeting the mid-2020s.",
  },
  {
    id: "andoya",
    name: "Andøya Space Center",
    shortName: "Andøya",
    lat: 69.2986,
    lon: 16.0143,
    country: "Norway",
    agency: "Andøya Space",
    firstLaunch: 1962,
    type: "gov",
    description: "Norway's rocket range on a North Sea island. Over 1,200 sounding rocket launches to date. New orbital launch pad (Andøya Spaceport) under development for European small satellites.",
  },
  {
    id: "saxavord",
    name: "SaxaVord Spaceport",
    shortName: "SaxaVord",
    lat: 60.8287,
    lon: -0.8726,
    country: "UK (Shetland)",
    agency: "SaxaVord / Rocket Lab / HMG",
    firstLaunch: 2024,
    type: "planned",
    description: "Europe's first vertical orbital launch site, on Unst in the Shetland Islands. Ideal for sun-synchronous and near-polar orbits with no overfly of populated land. Licensed to support Rocket Lab Neutron and other small launchers.",
  },
  {
    id: "spaceport-cornwall",
    name: "Spaceport Cornwall",
    shortName: "Cornwall",
    lat: 50.4402,
    lon: -5.0001,
    country: "UK",
    agency: "Virgin Orbit / HMG",
    firstLaunch: 2023,
    type: "historical",
    description: "First UK horizontal launch attempt in January 2023 using Virgin Orbit's LauncherOne rocket aboard a 747. The mission failed due to a fuel filter anomaly; Virgin Orbit subsequently declared bankruptcy. Site may be reused.",
  },
  // ── Asia ─────────────────────────────────────────────────────────
  {
    id: "jiuquan",
    name: "Jiuquan Satellite Launch Center",
    shortName: "Jiuquan",
    lat: 40.9583,
    lon: 100.2983,
    country: "China",
    agency: "CNSA / CASC",
    firstLaunch: 1970,
    type: "gov",
    description: "China's first launch center, deep in the Gobi Desert. Long March 2F carries Shenzhou crewed missions from here. Also home to Tianzhou cargo missions to the Chinese Space Station.",
  },
  {
    id: "xichang",
    name: "Xichang Satellite Launch Center",
    shortName: "Xichang",
    lat: 28.2462,
    lon: 102.0290,
    country: "China",
    agency: "CNSA / CASC",
    firstLaunch: 1984,
    type: "gov",
    description: "China's primary GEO and deep-space launch site. Launched the entire 35-satellite BeiDou-3 navigation constellation, as well as Chang'e lunar missions.",
  },
  {
    id: "wenchang",
    name: "Wenchang Space Launch Center",
    shortName: "Wenchang",
    lat: 19.6145,
    lon: 110.9510,
    country: "China",
    agency: "CNSA / CASC",
    firstLaunch: 2016,
    type: "gov",
    description: "China's southernmost and newest coastal launch center for heavy rockets. Long March 5/7 operate here. Launched Tianwen-1 to Mars, Chang'e-5 lunar return, and all CSS core/lab modules.",
  },
  {
    id: "taiyuan",
    name: "Taiyuan Satellite Launch Center",
    shortName: "Taiyuan",
    lat: 37.6987,
    lon: 112.5781,
    country: "China",
    agency: "CNSA / CASC",
    firstLaunch: 1988,
    type: "gov",
    description: "Primary Chinese site for polar and sun-synchronous missions. Launched Fengyun meteorological satellites, Ziyuan Earth-observation sats, and international commercial payloads.",
  },
  {
    id: "hainan-commercial",
    name: "Hainan International Commercial Aerospace Launch Center",
    shortName: "Hainan Comm.",
    lat: 19.5160,
    lon: 110.8590,
    country: "China",
    agency: "CAS Space / CASC Commercial",
    firstLaunch: 2022,
    type: "commercial",
    description: "China's new commercial launch complex adjacent to Wenchang, purpose-built for private launch providers. CAS Space's Kinetica-1 and CASC commercial Long March variants operate here.",
  },
  {
    id: "uchinoura",
    name: "Uchinoura Space Center",
    shortName: "Uchinoura",
    lat: 31.2513,
    lon: 131.0791,
    country: "Japan",
    agency: "JAXA",
    firstLaunch: 1962,
    type: "gov",
    description: "JAXA's science launch site, home of Japan's smallest orbital rockets. M-V (retired), Epsilon, and SS-520 flew from here. Launched the Hayabusa asteroid-sample return mission.",
  },
  {
    id: "tanegashima",
    name: "Tanegashima Space Center",
    shortName: "TNSC",
    lat: 30.3681,
    lon: 130.9680,
    country: "Japan",
    agency: "JAXA",
    firstLaunch: 1975,
    type: "gov",
    description: "Japan's main launch site for large rockets. H-IIA, H-IIB, and the new H3 operate from here, delivering HTV cargo to ISS and government/commercial satellites to GTO.",
  },
  {
    id: "sriharikota",
    name: "Satish Dhawan Space Centre",
    shortName: "SDSC-SHAR",
    lat: 13.7330,
    lon: 80.2350,
    country: "India",
    agency: "ISRO",
    firstLaunch: 1979,
    type: "gov",
    description: "India's spaceport on Sriharikota barrier island. Home of PSLV (India's workhorse), GSLV, and LVM3. Chandrayaan-3 (Moon south pole landing) and Aditya-L1 (solar observatory) launched here.",
  },
  {
    id: "naro",
    name: "Naro Space Center",
    shortName: "Naro",
    lat: 34.4320,
    lon: 127.5360,
    country: "South Korea",
    agency: "KARI",
    firstLaunch: 2009,
    type: "gov",
    description: "South Korea's first spaceport. After two KSLV-I partial failures, the Nuri (KSLV-II) rocket successfully reached orbit in 2022 — making South Korea the 10th nation to independently launch a satellite.",
  },
  {
    id: "sohae",
    name: "Sohae Satellite Launching Station",
    shortName: "Sohae",
    lat: 40.8514,
    lon: 124.7094,
    country: "North Korea",
    agency: "NADA / KCST",
    firstLaunch: 2012,
    type: "gov",
    description: "North Korea's primary orbital launch site on the Yellow Sea coast. Used for Kwangmyongsong and Malligyong reconnaissance satellite launches. Closely monitored by international agencies due to dual-use ICBM technology concerns.",
  },
  // ── Middle East ──────────────────────────────────────────────────
  {
    id: "palmachim",
    name: "Palmachim Air Force Base",
    shortName: "Palmachim",
    lat: 31.8940,
    lon: 34.6920,
    country: "Israel",
    agency: "IAI / ISA / IDF",
    firstLaunch: 1988,
    type: "gov",
    description: "Israel launches westward over the Mediterranean — opposite to Earth's rotation — to avoid overflying hostile territory. This costs ~1.5 km/s extra ΔV but is necessary for security. Home of the Shavit rocket.",
  },
  {
    id: "semnan",
    name: "Imam Khomeini Spaceport",
    shortName: "Semnan",
    lat: 35.2341,
    lon: 53.9211,
    country: "Iran",
    agency: "ISA / IRGC",
    firstLaunch: 2009,
    type: "gov",
    description: "Iran's primary space launch facility in Semnan Province. Safir and Simorgh rockets launched Omid, Navid, and Fajr satellites from here. Subject to international scrutiny due to ballistic missile overlap with the Safir/Simorgh vehicle stack.",
  },
  // ── Africa & Indian Ocean ─────────────────────────────────────────
  {
    id: "alcantara",
    name: "Alcântara Launch Center",
    shortName: "Alcântara",
    lat: -2.3706,
    lon: -44.3960,
    country: "Brazil",
    agency: "AEB / Embraer",
    firstLaunch: 1990,
    type: "gov",
    description: "Brazil's equatorial launch site — just 2.3° from the equator, one of Earth's best-positioned for GTO missions. A 2003 explosion killed 21 technicians; operations resumed in 2019. The AEB–USSF launch cooperation agreement now enables US vehicles to fly here.",
  },
  {
    id: "san-marco",
    name: "San Marco Platform",
    shortName: "San Marco",
    lat: -2.9381,
    lon: 40.2127,
    country: "Kenya",
    agency: "Italy / NASA (historical)",
    firstLaunch: 1967,
    type: "historical",
    description: "A converted oil-drilling platform 5 km off the Kenyan coast, operated by Italy's CRS Scuola. The world's first equatorial sea launch platform. Scout rockets orbited San Marco 1–5 satellites here (1967–1988). Now decommissioned.",
  },
  // ── Oceania ───────────────────────────────────────────────────────
  {
    id: "mahia",
    name: "Māhia Launch Complex 1",
    shortName: "Rocket Lab LC-1",
    lat: -39.2610,
    lon: 177.8650,
    country: "New Zealand",
    agency: "Rocket Lab",
    firstLaunch: 2017,
    type: "commercial",
    description: "Rocket Lab's private launch complex on the remote Māhia Peninsula. Can reach any inclination from 39°–98° without overflying populated areas. Electron has launched 40+ commercial payloads for NASA, DARPA, Planet Labs, and others.",
  },
  {
    id: "arnhem",
    name: "Arnhem Space Centre",
    shortName: "Arnhem",
    lat: -12.2300,
    lon: 136.8900,
    country: "Australia",
    agency: "Equatorial Launch Australia",
    firstLaunch: 2022,
    type: "commercial",
    description: "Australia's first commercial launch site in the Northern Territory. NASA launched its first rocket from Australian soil in over 25 years here in 2022, using Terran 1 on a sounding rocket campaign.",
  },
];

export function getLaunchSiteScenePos(site: LaunchSite, radiusOffset = 0.015): ScenePosition {
  return latLonToScene(site.lat, site.lon, EARTH_RADIUS_SCENE + radiusOffset);
}
