import { EARTH_RADIUS_SCENE } from "./constants";
import { latLonToScene, type ScenePosition } from "./coordinates";

export interface LaunchSite {
  id: string;
  name: string;
  shortName: string;
  lat: number;
  lon: number;
  country: string;
  agency: string;
  firstLaunch: number;
  description: string;
}

export const LAUNCH_SITES: LaunchSite[] = [
  {
    id: "ksc",
    name: "Kennedy Space Center / LC-39A",
    shortName: "KSC",
    lat: 28.5622,
    lon: -80.5772,
    country: "USA",
    agency: "NASA / SpaceX",
    firstLaunch: 1967,
    description: "Home of Apollo, Space Shuttle, and SpaceX Falcon 9/Heavy. LC-39A now supports Starship.",
  },
  {
    id: "canaveral",
    name: "Cape Canaveral SFS",
    shortName: "CC SFS",
    lat: 28.3922,
    lon: -80.6077,
    country: "USA",
    agency: "USSF / SpaceX / ULA",
    firstLaunch: 1950,
    description: "America's oldest active launch site. Atlas, Delta, and Falcon rockets lift off from here.",
  },
  {
    id: "baikonur",
    name: "Baikonur Cosmodrome",
    shortName: "Baikonur",
    lat: 45.9200,
    lon: 63.3420,
    country: "Kazakhstan",
    agency: "Roscosmos",
    firstLaunch: 1957,
    description: "World's first spaceport. Sputnik 1, Vostok 1 (Gagarin), and Soyuz crewed missions launched here.",
  },
  {
    id: "kourou",
    name: "Guiana Space Centre",
    shortName: "Kourou",
    lat: 5.2310,
    lon: -52.7690,
    country: "French Guiana",
    agency: "ESA / Arianespace",
    firstLaunch: 1968,
    description: "Near-equatorial location gives Ariane 5/6 a natural velocity boost for GTO missions.",
  },
  {
    id: "vandenberg",
    name: "Vandenberg SFB",
    shortName: "Vandenberg",
    lat: 34.7420,
    lon: -120.5724,
    country: "USA",
    agency: "USSF / SpaceX",
    firstLaunch: 1959,
    description: "Primary US site for polar and sun-synchronous orbits. SpaceX Falcon 9 launches frequently here.",
  },
  {
    id: "jiuquan",
    name: "Jiuquan Satellite Launch Center",
    shortName: "Jiuquan",
    lat: 40.9583,
    lon: 100.2983,
    country: "China",
    agency: "CNSA",
    firstLaunch: 1970,
    description: "China's first and oldest launch center in the Gobi Desert. Home of Shenzhou crewed missions.",
  },
  {
    id: "xichang",
    name: "Xichang Satellite Launch Center",
    shortName: "Xichang",
    lat: 28.2462,
    lon: 102.0290,
    country: "China",
    agency: "CNSA",
    firstLaunch: 1984,
    description: "China's primary GEO launch site. Launched the complete BeiDou navigation constellation.",
  },
  {
    id: "wenchang",
    name: "Wenchang Space Launch Center",
    shortName: "Wenchang",
    lat: 19.6145,
    lon: 110.9510,
    country: "China",
    agency: "CNSA",
    firstLaunch: 2016,
    description: "Modern coastal site for Long March 5/7. Launched China's Tianwen-1 Mars mission and CSS modules.",
  },
  {
    id: "plesetsk",
    name: "Plesetsk Cosmodrome",
    shortName: "Plesetsk",
    lat: 62.9270,
    lon: 40.6770,
    country: "Russia",
    agency: "Roscosmos / VKS",
    firstLaunch: 1966,
    description: "World's most prolific launch site by count. High latitude is ideal for polar reconnaissance orbits.",
  },
  {
    id: "sriharikota",
    name: "Satish Dhawan Space Centre",
    shortName: "SDSC-SHAR",
    lat: 13.7330,
    lon: 80.2350,
    country: "India",
    agency: "ISRO",
    firstLaunch: 1979,
    description: "India's spaceport on Sriharikota island. Home of PSLV, GSLV, and LVM3 rockets.",
  },
  {
    id: "tanegashima",
    name: "Tanegashima Space Center",
    shortName: "TNSC",
    lat: 30.3681,
    lon: 130.9680,
    country: "Japan",
    agency: "JAXA",
    firstLaunch: 1975,
    description: "Japan's main launch site. H-IIA/B and the new H3 rocket operate from here.",
  },
  {
    id: "mahia",
    name: "Māhia Launch Complex 1",
    shortName: "Rocket Lab",
    lat: -39.2610,
    lon: 177.8650,
    country: "New Zealand",
    agency: "Rocket Lab",
    firstLaunch: 2017,
    description: "Remote NZ peninsula enables launches to any inclination. Home of Rocket Lab's Electron rocket.",
  },
  {
    id: "wallops",
    name: "Wallops Flight Facility",
    shortName: "Wallops",
    lat: 37.8394,
    lon: -75.4874,
    country: "USA",
    agency: "NASA / Northrop Grumman",
    firstLaunch: 1945,
    description: "NASA's oldest launch site. Northrop Grumman Antares/Cygnus ISS resupply missions fly from here.",
  },
  {
    id: "alcantara",
    name: "Alcântara Launch Center",
    shortName: "Alcântara",
    lat: -2.3706,
    lon: -44.3960,
    country: "Brazil",
    agency: "AEB",
    firstLaunch: 1990,
    description: "Brazil's near-equatorial site — one of the best positions on Earth for GTO efficiency.",
  },
  {
    id: "naro",
    name: "Naro Space Center",
    shortName: "Naro",
    lat: 34.4320,
    lon: 127.5360,
    country: "South Korea",
    agency: "KARI",
    firstLaunch: 2009,
    description: "South Korea's spaceport. The KSLV-II Nuri rocket successfully reached orbit in 2022.",
  },
  {
    id: "taiyuan",
    name: "Taiyuan Satellite Launch Center",
    shortName: "Taiyuan",
    lat: 37.6987,
    lon: 112.5781,
    country: "China",
    agency: "CNSA",
    firstLaunch: 1988,
    description: "Specialises in polar and SSO missions. Launched Chinese meteorological and Earth-observation sats.",
  },
  {
    id: "esrange",
    name: "Esrange Space Center",
    shortName: "Esrange",
    lat: 67.8878,
    lon: 21.0854,
    country: "Sweden",
    agency: "SSC",
    firstLaunch: 1966,
    description: "Europe's northernmost launch site. Now expanding to orbital launches from the Arctic.",
  },
];

export function getLaunchSiteScenePos(site: LaunchSite, radiusOffset = 0.015): ScenePosition {
  return latLonToScene(site.lat, site.lon, EARTH_RADIUS_SCENE + radiusOffset);
}
